export type Region = '' | 'Africa' | 'Americas' | 'Asia' | 'Europe' | 'Oceania';
// | 'Northern Africa'
// | 'Sub-Saharan Africa'
// | 'Eastern Africa'
// | 'Middle Africa'
// | 'Southern Africa'
// | 'Western Africa	'
// | 'Latin America and the Caribbean'
// | 'Caribbean'
// | 'Central America'
// | 'South America'
// | 'Northern America'
// | 'Central Asia'
// | 'Eastern Asia'
// | 'South-eastern Asia'
// | 'Southern Asia'
// | 'Western Asia'
// | 'Eastern Europe'
// | 'Northern Europe'
// | 'Southern Europe'
// | 'Western Europe'
// | 'Australia and New Zealand'
// | 'Melanesia'
// | 'Micronesia'
// | 'Polynesia';
